# Generated by Django 4.2.5 on 2023-09-27 22:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='', variations={}, verbose_name='Image'),
        ),
    ]
