# Generated by Django 4.2.5 on 2023-09-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_register_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ativo',
            new_name='active',
        ),
    ]
