# Generated by Django 4.2.5 on 2023-09-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ativo_register_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(default='Default Status', max_length=100, verbose_name='Status'),
        ),
    ]
