# Generated by Django 4.2.5 on 2023-09-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_register_name_alter_register_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
    ]
