# Generated by Django 4.2.5 on 2023-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(default='Status indefinido!', max_length=100, verbose_name='Status'),
        ),
    ]
