# Generated by Django 4.2.5 on 2023-10-11 23:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='@senha1234', max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='registros', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
