# Generated by Django 4.2.5 on 2023-10-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_register_options_alter_register_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='active',
        ),
        migrations.RemoveField(
            model_name='register',
            name='creation',
        ),
    ]
