# Generated by Django 4.2.5 on 2023-10-26 02:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_register_active_remove_register_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='registros', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
