# Generated by Django 4.2.5 on 2023-10-31 23:22

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='posts', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
