# Generated by Django 4.2.5 on 2023-11-02 01:58

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_post_text_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, default='Sem foto', force_min_size=False, upload_to='posts', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=800, verbose_name='Digite seu texto'),
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, default='Sem foto', force_min_size=False, upload_to='registros', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
