# Generated by Django 4.2.5 on 2023-11-15 14:29

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_post_photo_alter_post_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, default='default_images/default_post.avif', force_min_size=False, upload_to='posts', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, default='default_images/default_user.avif', force_min_size=False, upload_to='registros', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
